apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p44pwxg29-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:1b0b55062835c9b7d0be8e584452b235f9e46d13@sha256:0648bfd5446885bbc0f07286734acb8ca9a5f92ed1d3fddaf106bfbeddd621b0
          name: container-image
